### ISSUE TITLE
Search Products by Tags but how about ?

### ISSUE THREAD

**Issue by matlus** [AzureCosmosDB/CosmicWorks#1]
Hello Thomas,
Eagerly awaiting your code, if not at least some guidance on how to do this. But what's more interesting would be:
Given a product (that has many tags) search related products. That is, to say, if the product has tags A, B, C, D, then return all products that have at least one of those tags and may order them by products that have the most matches.

**Comment by markjbrown** [comment]
If the product container can reside within a single physical partition, < 50GB you could do this with a query using a self-join to the tags array and a filter predicate on the tag name. However, if this was quite a bit larger than that, and also if this query was run at high concurrency, it would probably make more sense to use change feed to model the data such that you have products per tag, rather than tags per product which is what is shown in this solution here.

Thanks.
