### ISSUE TITLE
Unable to 'debug' modeling-demos application in Visual Studio

### ISSUE THREAD

**Issue by joehubbert** [AzureCosmosDB/CosmicWorks#22]
Hi Team,

When I try debugging the application after setting modeling-demos project as the startup project, I get the below error. I have ensured that all nuget packages are up to date

![image](https://user-images.githubusercontent.com/60545885/178277686-f7405788-7c6d-490b-a525-4e7497a69cb0.png)

**Comment by jaydestro** [comment]
@markjbrown @GaryHopeMS @ThomasWeiss 

I have replicated this issue with the current version of this repo in Visual Studio 19, 22 and VS Code

**Comment by joehubbert** [comment]
Thanks Mark! Creating a blank solution and adding the projects one by one did the trick. Any ideas why this might have happened?

**Comment by markjbrown** [comment]
There was a commit last Summer that got merged which contained a ton of garbage due to the .gitignore not being properly configured. I thought I had cleaned this up but it appears something is still not right.

I'm going to upgrade this to .NET 6 LTS here shortly. I'll rebuild the solution and project files from scratch just to ensure the repo is clean.

Thanks for reporting!
